### ISSUE TITLE
Can't get switch to work

### ISSUE THREAD

**Issue by sonderform** [dfdgsdfg/webflow-multilingual#1]
Hey there,

can you confirm the switch works? Everything else works for me, but not the switch. Can't figure it out.

**Comment by dfdgsdfg** [comment]
It seems to work.

Would you try like below?
<img width="234" alt="2018-12-12 12 22 25" src="https://user-images.githubusercontent.com/474775/49845113-c5693500-fe08-11e8-9070-c1bfd319a963.png">

**Comment by sonderform** [comment]
Works! I used it on already exported code and had it like that. Can't tell what the problem was :)
